const actionTypes = {
    "CAN_CASTLE" : "CAN_CASTLE",
    "STALEMATE" : "STALEMATE",
    "GENERATE_CANDIDATES_MOVES": "GENERATE_CANDIDATES_MOVES",
    "CLEAR_CANDIDATE_MOVES" : "CLEAR_CANDIDATE_MOVES",
    "NEW_MOVE" : "NEW_MOVE",
    "NEW_GAME" : "NEW_GAME",
    "PROMOTION_OPEN" : "PROMOTION_OPEN",
    "PROMOTION_CLOSE" : "PROMOTION_CLOSE"
}

export default actionTypes